# Generated by Django 4.1.7 on 2023-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('usd', 'Доллары США'), ('rub', 'Росийский Рубль'), ('eur', 'ЕВРО'), ('czk', 'Чешская Крона'), ('uah', 'Украниская Гривна')], max_length=3)),
            ],
        ),
    ]
