# Generated by Django 4.1.7 on 2023-02-19 15:55

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_item_image_alter_item_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Промокод')),
                ('discount_name', models.CharField(max_length=50, verbose_name='Уникальное имя')),
                ('percent_off', models.PositiveSmallIntegerField(validators=[items.models.percent_off_validation], verbose_name='Процент скидки')),
                ('duration', models.CharField(choices=[('once', 'Разовый'), ('forever', 'Постоянный'), ('repeating', 'Повторяющийся')], max_length=15, verbose_name='Продолжительность')),
                ('duration_in_months', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Продолжительность в месяцах')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('code', 'discount_name'), name='unique_discount'),
        ),
    ]
