# Generated by Django 4.1.7 on 2023-02-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_order_discount_unique_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['percent_off'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
