# Generated by Django 4.1.7 on 2023-02-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_discount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='duration_in_months',
        ),
    ]
