# Generated by Django 4.1.7 on 2023-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_order_options_order_created_at_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
