# Generated by Django 4.1.7 on 2023-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_discount_discount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prduct_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в платежной системе'),
        ),
    ]
