# Generated by Django 4.1.7 on 2023-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_prduct_id_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id в системе stripe'),
        ),
    ]
